add deployment steps

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,20 @@ on:
     branches:
       - main
 
+env:
+  RGLOCATION: southeastasia
+  RGNAME: rg-devcon-2021
+  PREFIX: daprdc
+  TFSTATERG: ${{ secrets.TFSTATERG }}
+  ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
+  ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
+  ARM_TENANT_ID: ${{ secrets.TENANTID }}
+  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
+  CERT: sp-cert
+  TFCLIENTID: ${{ secrets.TFCLIENTID }}
+  AKV_NAME: ${{ secrets.TFKV }}
+  ACRSERVER: ${{ secrets.ACRNAME }}.azurecr.io
+
 jobs:
   provision-infra:
     runs-on: ubuntu-latest
@@ -28,7 +42,7 @@ jobs:
         echo 'resource_group_name = "'${{ env.RGNAME }}'"' | tee -a terraform.tfvars
         echo 'aks_name = "aks-'${{ env.PREFIX }}'"' | tee -a terraform.tfvars
         echo 'arc_name = "arc-'${{ env.PREFIX }}'"' | tee -a terraform.tfvars
-        echo 'akv_name = "'${{ secrets.TFKV }}'"' | tee -a terraform.tfvars
+        echo 'akv_name = "'${{ env.AKV_NAME }}'"' | tee -a terraform.tfvars
         echo 'client_id = "'${{ env.ARM_CLIENT_ID }}'"' | tee -a terraform.tfvars
         echo 'client_secret = "'${{ env.ARM_CLIENT_SECRET }}'"' | tee -a terraform.tfvars
         echo 'subscription_id = "'${{ env.ARM_SUBSCRIPTION_ID }}'"' | tee -a terraform.tfvars
@@ -53,17 +67,8 @@ jobs:
         # Temporary steps
         az keyvault secret download --vault-name ${{ secrets.TFKV }} --name ${{ secrets.TFCERT }} --encoding base64 --file ${{ env.CERT }}.pfx
         az aks get-credentials --resource-group ${{ env.RGNAME }} --name aks-${{ env.PREFIX }}
+        kubectl delete secret ${{ env.CERT }} --ignore-not-found
         kubectl create secret generic ${{ env.CERT }} --from-file=./${{ env.CERT }}.pfx
-    env:
-      RGLOCATION: southeastasia
-      RGNAME: rg-devcon-2021
-      PREFIX: daprdc
-      TFSTATERG: ${{ secrets.TFSTATERG }}
-      ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
-      ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
-      ARM_TENANT_ID: ${{ secrets.TENANTID }}
-      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
-      CERT: sp-cert
   build:
     needs: provision-infra
     runs-on: ubuntu-latest
@@ -82,5 +87,23 @@ jobs:
         # if: github.event_name != 'pull_request'
         run: |
           REGISTRY=${{ env.ACRSERVER }} make push
-    env:
-      ACRSERVER: ${{ secrets.ACRNAME }}.azurecr.io
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@master
+    - name: AZ Login
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZCREDENTIALS }}
+    - name: Deploy Workload
+      run: |
+        # Exit when any command returns a failure status
+        set -e
+        cd ./deploy
+
+        # Temporary steps
+        az aks get-credentials --resource-group ${{ env.RGNAME }} --name aks-${{ env.PREFIX }}
+        envsubst < misc/azurekeyvault.yaml | kubectl apply -f -
+        kubectl apply -f misc/redis.yaml
+        kubectl apply -f .
